export const faArrowRight: IconDefinition;
export const faArrowUpRight: IconDefinition;
export const faSpinnerThird: IconDefinition;
export const faArrowLeft: IconDefinition;
export const faPresentationScreen: IconDefinition;
export const faPresentation: IconDefinition;
export const faCaretDown: IconDefinition;
export const faFileHeart: IconDefinition;
export const faArrowDown: IconDefinition;
export const faCheck: IconDefinition;
export const faNotdef: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fas: IconPack;